import React, { useEffect } from 'react'
import ArtItem from '../Arts/ArtItem'
import CartItem from './CartItem'
import { idbPromise } from '../../utils/helpers'
import Auth from '../../utils/auth'
import { TOGGLE_CART, ADD_TO_CART } from '../../utils/actions'
import { loadStripe } from '@stripe/stripe-js'
import { useLazyQuery } from '@apollo/client'
import { QUERY_CHECKOUT } from '../../utils/queries'
import { useStoreContext } from '../../utils/GlobalState'